export default interface AnimeAttributes {
  createdAt: string,
  updatedAt: string,
  slug: string,
  synopsis: string,
  coverImageTopOffset: number,
  titles: {
    en?: string,
    en_jp?: string,
    ja_jp?: string,
  },
  canonicalTitle: string,
  abbreviatedTitles: string[],
  averageRating: string,
  userCount: number,
  favoritesCount: number,
  startDate: string,
  endDate: string,
  popularityRank: number,
  ratingRank: number,
  ageRatingGuide: string,
  tba: string,
  episodeCount: number,
  episodeLength: number,
  youtubeVideoId: string,
}
